# Generated by Django 5.1.7 on 2025-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "Female"), (1, "Male")], default=1
                    ),
                ),
                (
                    "married",
                    models.IntegerField(choices=[(0, "Yes"), (1, "No")], default=0),
                ),
                (
                    "dependents",
                    models.CharField(
                        choices=[
                            ("0", "Zero"),
                            ("1", "First"),
                            ("2", "Two"),
                            ("3+", "Three Or More"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                (
                    "education",
                    models.IntegerField(
                        choices=[(0, "Not Graduate"), (1, "Graduate")], default=1
                    ),
                ),
                (
                    "self_employed",
                    models.IntegerField(choices=[(0, "Yes"), (1, "No")], default=1),
                ),
                ("applicant_income", models.IntegerField()),
                ("coapplicant_income", models.FloatField()),
                ("loan_amount", models.FloatField()),
                ("loan_amount_term", models.FloatField()),
                ("credit_history", models.FloatField()),
                (
                    "property_area",
                    models.IntegerField(
                        choices=[(0, "Semiurban"), (1, "Urban"), (2, "Rural")],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
