# Generated by Django 5.1.7 on 2025-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="credit_history",
            field=models.FloatField(
                choices=[("0.0", "No"), ("1.0", "Yes")], default="0.0"
            ),
        ),
    ]
