# Generated by Django 5.1.7 on 2025-03-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_client_credit_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="credit_history",
            field=models.FloatField(choices=[(0, "No"), (1, "Yes")], default=0),
        ),
    ]
