# Generated by Django 5.1.7 on 2025-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_client_credit_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="education",
            field=models.CharField(
                choices=[("Not Graduate", "Not Graduate"), ("Graduate", "Graduate")],
                default="Graduate",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                default="Male",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="married",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="property_area",
            field=models.CharField(
                choices=[
                    ("Semiurban", "Semiurban"),
                    ("Urban", "Urban"),
                    ("Rural", "Rural"),
                ],
                default="Urban",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="self_employed",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="No", max_length=3
            ),
        ),
    ]
