# Generated by Django 5.1.7 on 2025-03-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_client_education_alter_client_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="applicant_income",
            new_name="ApplicantIncome",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="coapplicant_income",
            new_name="CoapplicantIncome",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="credit_history",
            new_name="Credit_History",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="dependents",
            new_name="Dependents",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="education",
            new_name="Education",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="gender",
            new_name="Gender",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="loan_amount",
            new_name="LoanAmount",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="loan_amount_term",
            new_name="Loan_Amount_Term",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="married",
            new_name="Married",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="property_area",
            new_name="Property_Area",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="self_employed",
            new_name="Self_Employed",
        ),
    ]
